In [1]:
import pandas as pd
import numpy as np

### Load the dataset

In [2]:
df = pd.read_csv('iris.csv')

In [32]:
df

     sepal_length  sepal_width  petal_length  petal_width    species   rank
0             5.1          3.5           1.4          0.2     setosa   17.5
1             4.9          3.0           1.4          0.2     setosa   17.5
2             4.7          3.2           1.3          0.2     setosa    8.0
3             4.6          3.1           1.5          0.2     setosa   30.5
4             5.0          3.6           1.4          0.2     setosa   17.5
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica  117.5
146           6.3          2.5           5.0          1.9  virginica  106.5
147           6.5          3.0           5.2          2.0  virginica  117.5
148           6.2          3.4           5.4          2.3  virginica  121.5
149           5.9          3.0           5.1          1.8  virginica  112.5

[150 rows x 6 columns]

### Group by species

In [33]:
df.groupby(['species'])
df

     sepal_length  sepal_width  petal_length  petal_width    species   rank
0             5.1          3.5           1.4          0.2     setosa   17.5
1             4.9          3.0           1.4          0.2     setosa   17.5
2             4.7          3.2           1.3          0.2     setosa    8.0
3             4.6          3.1           1.5          0.2     setosa   30.5
4             5.0          3.6           1.4          0.2     setosa   17.5
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica  117.5
146           6.3          2.5           5.0          1.9  virginica  106.5
147           6.5          3.0           5.2          2.0  virginica  117.5
148           6.2          3.4           5.4          2.3  virginica  121.5
149           5.9          3.0           5.1          1.8  virginica  112.5

[150 rows x 6 columns]

### Descriptive stats for the groups

In [38]:
df.describe()
df.groupby('species').describe()

           sepal_length
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8  \
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_width       rank
                 count   mean  ...         75%  max count    mean        std
species                        ...
setosa            50.0  3.418  ...         0.3  0.6  50.0   25.50  14.271421  \
versicolor        50.0  2.770  ...         1.5  1.8  50.0   76.39  15.901896
virginica         50.0  2.974  ...         2.3  2.5  50.0  124.61  16.058023


             min    25%     50%      75%    max
species
setosa       1.0   17.5   30.50   38.375   49.5
versicolor  51.0   64.0   76.00   89.000  112.5
virginica   83.5  112.5  126.25  137.875  150.0

[3 rows x 40 columns]

### Ranking the petal length in an ascending order

In [47]:
df['rank'] = df['petal_length'].rank()
df.sort_values('rank', ascending=True)

     sepal_length  sepal_width  petal_length  petal_width    species   rank
22            4.6          3.6           1.0          0.2     setosa    1.0
13            4.3          3.0           1.1          0.1     setosa    2.0
14            5.8          4.0           1.2          0.2     setosa    3.5
35            5.0          3.2           1.2          0.2     setosa    3.5
36            5.5          3.5           1.3          0.2     setosa    8.0
..            ...          ...           ...          ...        ...    ...
131           7.9          3.8           6.4          2.0  virginica  146.0
105           7.6          3.0           6.6          2.1  virginica  147.0
117           7.7          3.8           6.7          2.2  virginica  148.5
122           7.7          2.8           6.7          2.0  virginica  148.5
118           7.7          2.6           6.9          2.3  virginica  150.0

[150 rows x 6 columns]

### Mean of each column for each species

In [48]:
df.groupby(['species']).mean()

            sepal_length  sepal_width  petal_length  petal_width    rank
species
setosa             5.006        3.418         1.464        0.244   25.50
versicolor         5.936        2.770         4.260        1.326   76.39
virginica          6.588        2.974         5.552        2.026  124.61

### DataFrame for each of the species separately, with each index starting at 0

In [50]:
df_setosa = df.groupby('species').get_group('setosa')
df_setosa

    sepal_length  sepal_width  petal_length  petal_width species  rank
0            5.1          3.5           1.4          0.2  setosa  17.5
1            4.9          3.0           1.4          0.2  setosa  17.5
2            4.7          3.2           1.3          0.2  setosa   8.0
3            4.6          3.1           1.5          0.2  setosa  30.5
4            5.0          3.6           1.4          0.2  setosa  17.5
5            5.4          3.9           1.7          0.4  setosa  46.5
6            4.6          3.4           1.4          0.3  setosa  17.5
7            5.0          3.4           1.5          0.2  setosa  30.5
8            4.4          2.9           1.4          0.2  setosa  17.5
9            4.9          3.1           1.5          0.1  setosa  30.5
10           5.4          3.7           1.5          0.2  setosa  30.5
11           4.8          3.4           1.6          0.2  setosa  41.0
12           4.8          3.0           1.4          0.1  setosa  17.5
13           4.3          3.0           1.1          0.1  setosa   2.0
14           5.8          4.0           1.2          0.2  setosa   3.5
15           5.7          4.4           1.5          0.4  setosa  30.5
16           5.4          3.9           1.3          0.4  setosa   8.0
17           5.1          3.5           1.4          0.3  setosa  17.5
18           5.7          3.8           1.7          0.3  setosa  46.5
19           5.1          3.8           1.5          0.3  setosa  30.5
20           5.4          3.4           1.7          0.2  setosa  46.5
21           5.1          3.7           1.5          0.4  setosa  30.5
22           4.6          3.6           1.0          0.2  setosa   1.0
23           5.1          3.3           1.7          0.5  setosa  46.5
24           4.8          3.4           1.9          0.2  setosa  49.5
25           5.0          3.0           1.6          0.2  setosa  41.0
26           5.0          3.4           1.6          0.4  setosa  41.0
27           5.2          3.5           1.5          0.2  setosa  30.5
28           5.2          3.4           1.4          0.2  setosa  17.5
29           4.7          3.2           1.6          0.2  setosa  41.0
30           4.8          3.1           1.6          0.2  setosa  41.0
31           5.4          3.4           1.5          0.4  setosa  30.5
32           5.2          4.1           1.5          0.1  setosa  30.5
33           5.5          4.2           1.4          0.2  setosa  17.5
34           4.9          3.1           1.5          0.1  setosa  30.5
35           5.0          3.2           1.2          0.2  setosa   3.5
36           5.5          3.5           1.3          0.2  setosa   8.0
37           4.9          3.1           1.5          0.1  setosa  30.5
38           4.4          3.0           1.3          0.2  setosa   8.0
39           5.1          3.4           1.5          0.2  setosa  30.5
40           5.0          3.5           1.3          0.3  setosa   8.0
41           4.5          2.3           1.3          0.3  setosa   8.0
42           4.4          3.2           1.3          0.2  setosa   8.0
43           5.0          3.5           1.6          0.6  setosa  41.0
44           5.1          3.8           1.9          0.4  setosa  49.5
45           4.8          3.0           1.4          0.3  setosa  17.5
46           5.1          3.8           1.6          0.2  setosa  41.0
47           4.6          3.2           1.4          0.2  setosa  17.5
48           5.3          3.7           1.5          0.2  setosa  30.5
49           5.0          3.3           1.4          0.2  setosa  17.5

In [22]:
df_virginica = df.groupby('species').get_group('virginica').reset_index()
df_virginica

,index,sepal_length,sepal_width,petal_length,petal_width,species,rank
0,100,6.3,3.3,6.0,2.5,virginica,140.5
1,101,5.8,2.7,5.1,1.9,virginica,112.5
2,102,7.1,3.0,5.9,2.1,virginica,138.5
3,103,6.3,2.9,5.6,1.8,virginica,128.5
4,104,6.5,3.0,5.8,2.2,virginica,136.0
5,105,7.6,3.0,6.6,2.1,virginica,147.0
6,106,4.9,2.5,4.5,1.7,virginica,83.5
7,107,7.3,2.9,6.3,1.8,virginica,145.0
8,108,6.7,2.5,5.8,1.8,virginica,136.0
9,109,7.2,3.6,6.1,2.5,virginica,143.0
10,110,6.5,3.2,5.1,2.0,virginica,112.5
11,111,6.4,2.7,5.3,1.9,virginica,119.5
12,112,6.8,3.0,5.5,2.1,virginica,124.0
13,113,5.7,2.5,5.0,2.0,virginica,106.5
14,114,5.8,2.8,5.1,2.4,virginica,112.5
15,115,6.4,3.2,5.3,2.3,virginica,119.5
16,116,6.5,3.0,5.5,1.8,virginica,124.0
17,117,7.7,3.8,6.7,2.2,virginica,148.5
18,118,7.7,2.6,6.9,2.3,virginica,150.0
19,119,6.0,2.2,5.0,1.5,virginica,106.5
20,120,6.9,3.2,5.7,2.3,virginica,133.0
21,121,5.6,2.8,4.9,2.0,virginica,102.0
22,122,7.7,2.8,6.7,2.0,virginica,148.5
23,123,6.3,2.7,4.9,1.8,virginica,102.0
24,124,6.7,3.3,5.7,2.1,virginica,133.0
25,125,7.2,3.2,6.0,1.8,virginica,140.5
26,126,6.2,2.8,4.8,1.8,virginica,97.5
27,127,6.1,3.0,4.9,1.8,virginica,102.0
28,128,6.4,2.8,5.6,2.1,virginica,128.5
29,129,7.2,3.0,5.8,1.6,virginica,136.0
30,130,7.4,2.8,6.1,1.9,virginica,143.0
31,131,7.9,3.8,6.4,2.0,virginica,146.0
32,132,6.4,2.8,5.6,2.2,virginica,128.5
33,133,6.3,2.8,5.1,1.5,virginica,112.5
34,134,6.1,2.6,5.6,1.4,virginica,128.5
35,135,7.7,3.0,6.1,2.3,virginica,143.0
36,136,6.3,3.4,5.6,2.4,virginica,128.5
37,137,6.4,3.1,5.5,1.8,virginica,124.0
38,138,6.0,3.0,4.8,1.8,virginica,97.5
39,139,6.9,3.1,5.4,2.1,virginica,121.5
40,140,6.7,3.1,5.6,2.4,virginica,128.5
41,141,6.9,3.1,5.1,2.3,virginica,112.5
42,142,5.8,2.7,5.1,1.9,virginica,112.5
43,143,6.8,3.2,5.9,2.3,virginica,138.5
44,144,6.7,3.3,5.7,2.5,virginica,133.0
45,145,6.7,3.0,5.2,2.3,virginica,117.5
46,146,6.3,2.5,5.0,1.9,virginica,106.5
47,147,6.5,3.0,5.2,2.0,virginica,117.5
48,148,6.2,3.4,5.4,2.3,virginica,121.5
49,149,5.9,3.0,5.1,1.8,virginica,112.5

In [23]:
df_versicolor = df.groupby('species').get_group('versicolor').reset_index()
df_versicolor

,index,sepal_length,sepal_width,petal_length,petal_width,species,rank
0,50,7.0,3.2,4.7,1.4,versicolor,93.0
1,51,6.4,3.2,4.5,1.5,versicolor,83.5
2,52,6.9,3.1,4.9,1.5,versicolor,102.0
3,53,5.5,2.3,4.0,1.3,versicolor,64.0
4,54,6.5,2.8,4.6,1.5,versicolor,89.0
5,55,5.7,2.8,4.5,1.3,versicolor,83.5
6,56,6.3,3.3,4.7,1.6,versicolor,93.0
7,57,4.9,2.4,3.3,1.0,versicolor,52.5
8,58,6.6,2.9,4.6,1.3,versicolor,89.0
9,59,5.2,2.7,3.9,1.4,versicolor,60.0
10,60,5.0,2.0,3.5,1.0,versicolor,54.5
11,61,5.9,3.0,4.2,1.5,versicolor,71.5
12,62,6.0,2.2,4.0,1.0,versicolor,64.0
13,63,6.1,2.9,4.7,1.4,versicolor,93.0
14,64,5.6,2.9,3.6,1.3,versicolor,56.0
15,65,6.7,3.1,4.4,1.4,versicolor,77.5
16,66,5.6,3.0,4.5,1.5,versicolor,83.5
17,67,5.8,2.7,4.1,1.0,versicolor,68.0
18,68,6.2,2.2,4.5,1.5,versicolor,83.5
19,69,5.6,2.5,3.9,1.1,versicolor,60.0
20,70,5.9,3.2,4.8,1.8,versicolor,97.5
21,71,6.1,2.8,4.0,1.3,versicolor,64.0
22,72,6.3,2.5,4.9,1.5,versicolor,102.0
23,73,6.1,2.8,4.7,1.2,versicolor,93.0
24,74,6.4,2.9,4.3,1.3,versicolor,74.5
25,75,6.6,3.0,4.4,1.4,versicolor,77.5
26,76,6.8,2.8,4.8,1.4,versicolor,97.5
27,77,6.7,3.0,5.0,1.7,versicolor,106.5
28,78,6.0,2.9,4.5,1.5,versicolor,83.5
29,79,5.7,2.6,3.5,1.0,versicolor,54.5
30,80,5.5,2.4,3.8,1.1,versicolor,58.0
31,81,5.5,2.4,3.7,1.0,versicolor,57.0
32,82,5.8,2.7,3.9,1.2,versicolor,60.0
33,83,6.0,2.7,5.1,1.6,versicolor,112.5
34,84,5.4,3.0,4.5,1.5,versicolor,83.5
35,85,6.0,3.4,4.5,1.6,versicolor,83.5
36,86,6.7,3.1,4.7,1.5,versicolor,93.0
37,87,6.3,2.3,4.4,1.3,versicolor,77.5
38,88,5.6,3.0,4.1,1.3,versicolor,68.0
39,89,5.5,2.5,4.0,1.3,versicolor,64.0
40,90,5.5,2.6,4.4,1.2,versicolor,77.5
41,91,6.1,3.0,4.6,1.4,versicolor,89.0
42,92,5.8,2.6,4.0,1.2,versicolor,64.0
43,93,5.0,2.3,3.3,1.0,versicolor,52.5
44,94,5.6,2.7,4.2,1.3,versicolor,71.5
45,95,5.7,3.0,4.2,1.2,versicolor,71.5
46,96,5.7,2.9,4.2,1.3,versicolor,71.5
47,97,6.2,2.9,4.3,1.3,versicolor,74.5
48,98,5.1,2.5,3.0,1.1,versicolor,51.0
49,99,5.7,2.8,4.1,1.3,versicolor,68.0

### Two seperate dataframes, one for the Sepal information and one for the Petal information

In [51]:
df_sepal_info = df.filter(['sepal_length', 'sepal_width', 'species'], axis=1)
df_sepal_info

     sepal_length  sepal_width    species
0             5.1          3.5     setosa
1             4.9          3.0     setosa
2             4.7          3.2     setosa
3             4.6          3.1     setosa
4             5.0          3.6     setosa
..            ...          ...        ...
145           6.7          3.0  virginica
146           6.3          2.5  virginica
147           6.5          3.0  virginica
148           6.2          3.4  virginica
149           5.9          3.0  virginica

[150 rows x 3 columns]